name: first_one
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Lint
      run: ddd
    - name: Test
      run: ddd
    - name: Build
      run: ddd
    - name:  Message
      run: echo "Output message"
      
